services:
  gnuboard6:
    image: navystack/gnuboard-g6:nightly-latest
    restart: always
    logging:
      options:
        max-size: "10m"
    volumes:
      - gnuboard6-data:/g6
    ports:
      - "8000:8000"

  gnuboard6-postgresql:
    image: postgres:16-bullseye
    restart: always
    logging:
      options:
        max-size: "10m"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "6VqahNQruCdfnzKSFaUmE8pUd2o7Ee"
    volumes:
      - postgresql_database:/var/lib/postgresql/data

volumes:
  postgresql_database:
  gnuboard6-data:
