name: Nightly Build

on:
  schedule:
    - cron: "0 15 * * *" # UTC time for 00:00 KST
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "./docker/bookworm/Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: navystack/gnuboard-g6

      #- name: Set up QEMU
      #  uses: docker/setup-qemu-action@v3

      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v3

      - name: Set up SSH
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: ${{ secrets.SSH_ARM64_RUNNER }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY_ARM64_RUNNER }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: ${{ secrets.AMD64_RUNNER_ENDPOINT }}
          append: |
            - endpoint: ${{ secrets.ARM64_RUNNER_ENDPOINT }}
              platforms: linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set lowercase repository owner
        run: |
          repo_owner_lowercase=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_OWNER_LOWERCASE=$repo_owner_lowercase" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.REPO_OWNER_LOWERCASE }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date in KST
        run: echo "CURRENT_DATE_KST=$(date +'%Y%m%d-%H%M%S' -d '+9 hours')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: docker/bookworm/Dockerfile
          push: true
          pull: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/gnuboard-g6:nightly-${{ env.CURRENT_DATE_KST }}
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/gnuboard-g6:nightly-latest
            ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/gnuboard-g6:nightly
            navystack/gnuboard-g6:nightly-${{ env.CURRENT_DATE_KST }}
            navystack/gnuboard-g6:nightly-latest
            navystack/gnuboard-g6:nightly
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
